Ligerui/LED/LED.WebUI/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LED.Domain.IRepository;
using LED.Domain.Entities;

namespace LED.WebUI.Controllers
{
   
    public class MenuController : Controller
    {
        //
        // GET: /Menu/

        private IMenuRepository _menuRepository;

        public MenuController(IMenuRepository menuRepository)
        {

            this._menuRepository = menuRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult MenuDataSource()
        {

            var data = _menuRepository.GetMenuParentsNode().ToList();

            var list = new List<dynamic>();

            foreach (var item in data)
            {
                var children = _menuRepository.GetMenuChildrenNodeByParentId(item.rid).ToList();

                if (children == null || children.Count() == 0)
                {
                    list.Add(new
                    {
                        name = item.name, 
                        tindex = item.tindex,
                        url = item.url,
                        rid=item.rid,
                        parentrid = item.parentrid
                    });
                }
                else
                {
                    list.Add(new
                    {
                        name = item.name,
                        tindex = item.tindex,
                        url = item.url,
                        rid = item.rid,
                        parentrid = item.parentrid,
                        children = children.Select(m => new {
                            name = m.name,
                            tindex = m.tindex,
                            url = m.url,
                            rid = m.rid,
                            parentrid = m.parentrid
                        })
                    });
                }
            }

            return Json(new
            {
                Rows = list,
                Total = list.Count()
            }, JsonRequestBehavior.AllowGet);

        }

        public JsonResult ParentNode()
        {

            var data = _menuRepository.GetMenuParentsNode().ToList();

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AddMenu(int? parentNode, string pageName, string url,int?index)
        {
            var check = _menuRepository.GetMenuByCondition(pageName, url);

            if (check.Count() > 1)
            {
                return Json(new { result = false, msg = "修改失败，已存在相同的菜单！" }, JsonRequestBehavior.AllowGet);
            }
            var menu = new t_resources()
            {
                name = pageName,
                url = url,
                parentrid = parentNode,
                tindex=index
            };

            try
            {
              var result= _menuRepository.AddMenu(menu);
              if (result)
              {
                  return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
              }
              else
              {
                  return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
              }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult DeleteMenu(int rid)
        {
            var menu = new t_resources()
            {
                rid=rid
            };

            try
            {
                var result = _menuRepository.DeleteMenu(menu);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult ModifyMenu(string pageName, int? index, string url, int rid, int? parentrid)
        {
            var check = _menuRepository.GetMenuByCondition(pageName,url);

            if (check.Count() > 1) {
                return Json(new { result = false, msg = "修改失败，已存在相同的菜单！" }, JsonRequestBehavior.AllowGet);
            }

            var menu = new t_resources()
            {
                name=pageName,
                tindex=index,
                url=url,
                rid=rid,
                parentrid=parentrid
            };

            try
            {
                var result = _menuRepository.UpdateMenu(menu);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Ligerui/LED/LED.WebUI/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LED.Domain.IRepository;
using LED.Domain.Entities;

namespace LED.WebUI.Controllers
{
 
    public class RoleController : Controller
    {
        //
        // GET: /Role/ 

        private IRoleRepository _roleRepository;
        private IOrgRepository _orgRepository;
        private IMenuRepository _menuRepository;

        public RoleController(IRoleRepository roleRepository, IOrgRepository orgRepository, IMenuRepository menuRepository)
        {

            this._roleRepository = roleRepository;
            this._orgRepository = orgRepository;
            this._menuRepository = menuRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult RoleDataSource()
        {
            var data = _roleRepository.GetAll().ToList();

            return Json(new
            {
                Rows = data.Select(m => new
                {
                    roleid = m.roleid,
                    rolename = m.rolename

                }),
                Total = data.Count()
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult RoleDetail(int roleId)
        {
            var data = _roleRepository.GetUserByRoleId(roleId).ToList();

            return Json(new
            {
                Rows = data.Select(m => new
                {
                    userid = m.userid,
                    name = m.name,
                    roleid = roleId
                }),
                Total = data.Count()
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AddRole(int roleId, string roleName)
        {
            var check = _roleRepository.GetRoleByConditon(roleId, roleName);

            if (check.Count() > 1)
            {
                return Json(new { result = false, msg = "添加失败，不能重复添加相同的角色！" }, JsonRequestBehavior.AllowGet);
            }

            try
            {
                var role = new t_role
                {
                    roleid = roleId,
                    rolename = roleName
                };
                var result = _roleRepository.AddRole(role);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult ModifyRole(int roleId, string roleName)
        {
            var check = _roleRepository.GetRoleByConditon(roleId, roleName);

            if (check.Count() > 1)
            {
                return Json(new { result = false, msg = "添加失败，不能修改为相同的角色！" }, JsonRequestBehavior.AllowGet);
            }

            try
            {
                var role = new t_role
                {
                    roleid = roleId,
                    rolename = roleName
                };
                var result = _roleRepository.ModifyRole(role);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult DeleteRole(int roleId)
        {
            var role = new t_role
            {
                roleid = roleId

            };

            try
            {
                var result = _roleRepository.DeleteRole(role);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult MenuDataSource()
        {

            var data = _menuRepository.GetMenuAll().ToList();

            return Json(new { Rows = data.Select(m => new { name = m.name, rid = m.rid }), Total = data.Count() }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AttachRoleToMenu(int roleId, List<int> menus)
        {
            try
            {
                var result = _roleRepository.AttachRoleToMenu(roleId, menus);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetMenuByRoleId(int roleId)
        {
            var data = _roleRepository.GetMenuByRoleId(roleId).Select(m=>m.rid).ToArray();

            return Json(data,JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteUserFromRole(string userId,int roleId) {

            try
            {
                var result = _roleRepository.DeleteUserFromRole(userId,roleId);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Ligerui/LED/LED.WebUI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LED.Domain.IRepository;
using LED.Domain.Entities;

namespace LED.WebUI.Controllers
{

    public class UserController : Controller
    {
        //
        // GET: /User/

        private IUserRepository _userRepository;
        private IOrgRepository _orgRepository;
        private IRoleRepository _roleRepository;

        public UserController(IUserRepository userRepository, IOrgRepository orgRepository, IRoleRepository roleRepository)
        {
            this._userRepository = userRepository;
            this._orgRepository = orgRepository;
            this._roleRepository = roleRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult TreeDataSource()
        {
            var data = _orgRepository.GetOrgAll().ToList().Select(m => new
            {

                orgCode = m.orgcode,
                name = m.name,
                parentCode = m.parentCode
            });

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UserDataSource(string orgCode)
        {
            var data = _userRepository.GetUserByOrgCode(orgCode).ToList();
            return Json(new
            {
                Rows = data.Select(m => new
                {
                    userid = m.userid,
                    name = m.name,
                    rolename = string.Join(",", m.role == null ? new string[] { "" } : m.role.ToList().Select(r => r.rolename).Distinct())
                }),
                Total = data.Count()
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AddUser(string orgCode, string userId, string userName, string password)
        {
            var check = _userRepository.GetUserBySpecifiedCondition(userId);

            if (check.Count() > 1)
            {
                return Json(new { result = false, msg = "添加失败，已存在相同的用户账号！" }, JsonRequestBehavior.AllowGet);
            }

            var org = new t_user()
            {
                orgcode = orgCode,
                userid = userId,
                name = userName,
                password = password

            };

            try
            {
                var result = _userRepository.AddUser(org);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult ModifyUser(string userId, string userName, string password)
        {

            var org = new t_user()
            {
                userid = userId,
                name = userName,
                password = password

            };

            try
            {
                var result = _userRepository.ModifyUser(org);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult DeleteUser(string userId)
        {
            try
            {
                var result = _userRepository.DeleteUser(userId);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult AddRole(string userId, string userName, string roleName)
        {
            var check = _userRepository.GetUserRoleByCondition(userName, roleName);

            if (check.Count() > 1)
            {
                return Json(new { result = false, msg = "添加失败，不能重复添加相同的角色！" }, JsonRequestBehavior.AllowGet);
            }

            try
            {
                var result = _userRepository.AddRole(userId, userName, roleName);
                if (result)
                {
                    return Json(new { result = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, msg = "操作失败！" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { result = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetRole()
        {

            var data = _roleRepository
                .GetAll()
                .ToList()
                .Select(m => new
                {
                    roleid = m.roleid,
                    rolename = m.rolename
                });

            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

Ligerui/LED/LED.WebUI/Views/Home/Index.cshtml
@section headerScripts{
    <style type="text/css">
        .l-case-title {
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        body, html {
            width: 100%;
            height: 100%;
        }

        * {
            margin: 0;
            padding: 0;
        }

        #winlinks {
            position: absolute;
            left: 20px;
            top: 20px;
            width: 100%;
        }

            #winlinks ul {
                position: relative;
            }

            #winlinks li {
                width: 70px;
                cursor: pointer;
                height: 80px;
                position: absolute;
                z-index: 101;
                list-style: none;
                text-align: center;
            }

                #winlinks li img {
                    width: 36px;
                    height: 36px;
                }

                #winlinks li span {
                    background: none repeat scroll 0 0 rgba(0, 0, 0, 0.3);
                    border-radius: 10px 10px 10px 10px;
                    display: block;
                    font-size: 12px;
                    margin-top: 1px;
                    color: White;
                    line-height: 18px;
                    text-align: center;
                }

                #winlinks li.l-over div.bg {
                    display: block;
                }

                #winlinks li div.bg {
                    display: none;
                    position: absolute;
                    top: -2px;
                    left: -2px;
                    z-index: 0;
                    width: 75px;
                    height: 64px;
                    -webkit-border-radius: 5px;
                    -moz-border-radius: 5px;
                    border-radius: 5px;
                    background: #000;
                    opacity: 0.1;
                    filter: alpha(opacity=10);
                }

        .l-taskbar-task-icon {
            top: 3px;
            left: 6px;
            background-image: none;
        }

        .l-taskbar-task-content {
            margin-left: 30px;
        }

        .l-taskbar-task-icon img {
            width: 22px;
            height: 22px;
        }

        body {
            overflow: hidden;
            background: url(Content/LigerUI/images/5.png) repeat center center;
        }
    </style>

    <script type="text/javascript">
        var UrlOrg = '@Url.Action("Index", "Organization")';
        var UrlMenu = '@Url.Action("Index", "Menu")';
        var UrlUser = '@Url.Action("Index", "User")';
        var UrlRole = '@Url.Action("Index", "Role")';
        var UrlDevice = '';
        var UrlProgram = '';
        var UrlLog = '';
        var UrlSystem = '';
        var UrlBack = '';
        var directory = 'Content/LigerUI/skins_1/';
    </script>
}

<div id="winlinks">
    <ul>
    </ul>
</div>

@section bottomScripts{
    <script type="text/javascript">
        var LINKWIDTH = 90, LINKHEIGHT = 90, TASKBARHEIGHT = 43;
        var winlinksul = $("#winlinks ul");
        function winOpen(url, title, icon, width, height) {
            var win = $.ligerDialog.open(
            {
                height: height,
                url: url,
                width: width,
                showMax: false,
                showToggle: true,
                showMin: true,
                isResize: true,
                modal: false,
                title: title,
                slide: true
            });
            var task = jQuery.ligerui.win.tasks[win.id];
            if (task) {
                $(".l-taskbar-task-icon:first", task).html('<img src="' + icon + '" />');
            }
            return win;
        }
        var links = [
                { icon: directory + 'Filezilla.png', title: '组织结构管理', url: UrlOrg, width: 960, height: 600 },
                { icon: directory + 'Recycle Empty.png', title: '菜单管理', url: UrlMenu, width: 970, height: 600 },
                { icon: directory + 'Steam.png', title: '用户管理', url: UrlUser, width: 960, height: 600 },
                { icon: directory + 'Notepad.png', title: '角色管理', url: UrlRole, width: 960, height: 600 },
                { icon: directory + 'picassa.png', title: '某某管理', url: UrlDevice, width: 960, height: 600 },
                { icon: directory + 'Recycle Full.png', title: '某某管理1', url: UrlProgram, width: 960, height: 600 },
                { icon: directory + 'SoulSeek.png', title: '某某管理2', url: UrlLog, width: 960, height: 600 },
                { icon: directory + 'Task Manager.png', title: '某某管理3', url: UrlBack, width: 960, height: 600 }
        ];

        function onResize() {
            var linksHeight = $(window).height() - TASKBARHEIGHT;
            var winlinks = $("#winlinks");
            winlinks.height(linksHeight);
            var colMaxNumber = parseInt(linksHeight / LINKHEIGHT);//一列最多显示几个快捷方式
            for (var i = 0, l = links.length; i < l; i++) {
                var link = links[i];
                var jlink = $("li[linkindex=" + i + "]", winlinks);
                var top = (i % colMaxNumber) * LINKHEIGHT, left = parseInt(i / colMaxNumber) * LINKWIDTH;
                if (isNaN(top) || isNaN(left)) continue;
                jlink.css({ top: top, left: left });
            }

        }
        function linksInit() {
            for (var i = 0, l = links.length; i < l; i++) {
                var link = links[i];
                var jlink;
                var jlink = $("<li></li>");
                jlink.attr("linkindex", i);
                jlink.append("<img src='" + link.icon + "' />");
                jlink.append("<span>" + link.title + "</span>");
                jlink.append("<div class='bg'></div>");
                jlink.hover(function () {
                    $(this).addClass("l-over");
                }, function () {
                    $(this).removeClass("l-over");
                }).click(function () {
                    var linkindex = $(this).attr("linkindex");
                    var link = links[linkindex];
                    winOpen(link.url, link.title, link.icon, link.width, link.height);
                });
                jlink.appendTo(winlinksul);
            }

        }

        $(window).resize(onResize);
        $.ligerui.win.removeTaskbar = function () { }; //不允许移除
        $.ligerui.win.createTaskbar(); //页面加载时创建任务栏

        linksInit();
        onResize();

    </script>
}